package com.typenull.pingdom.shared.outbox.domain;

public enum OutboxEventType {
    EMAIL_VERIFICATION_REQUESTED,
    PASSWORD_RESET_REQUESTED,
    MAP_IMAGE_LIKED,
    PLACE_RECOMMENDATION_RESYNC_REQUESTED,
    PLACE_INFORMATION_EVIDENCE_SUBMITTED,
    PLACE_INFORMATION_VERIFICATION_UPDATED,
    PLACE_INFORMATION_REPORT_SUBMITTED,
    PLACE_INFORMATION_REPORT_DISPUTED,
    PLACE_INFORMATION_REPORT_REVIEWED,
    PLACE_INFORMATION_DISPUTE_SUBMITTED,
    PLACE_INFORMATION_DISPUTE_REVIEWED,
    PLACE_INFORMATION_REVERIFICATION_REQUESTED,
    PLACE_INFORMATION_REVERIFICATION_REMINDER_REQUESTED,
    PLACE_OPERATING_NOTICE_CREATED,
    PLACE_OPERATING_NOTICE_UPDATED,
    PLACE_OPERATING_NOTICE_EXPIRED,
    PLACE_OPERATING_NOTICE_CANCELED,
    PLACE_CONVERSION_RECORDED,
    S3_OBJECT_DELETE_REQUESTED
}
