package com.typenull.pingdom.moderation.domain.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum AdminErrorCode {
    ADMIN_ROLE_ASSIGNMENT_INVALID(HttpStatus.BAD_REQUEST, "관리자 역할 할당 요청이 올바르지 않습니다."),
    ADMIN_PERMISSION_REQUIRED(HttpStatus.FORBIDDEN, "요청을 처리할 관리자 권한이 없습니다."),
    ADMIN_ROLE_ASSIGNMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "관리자 역할 할당을 찾을 수 없습니다."),
    ADMIN_ROLE_ASSIGNMENT_CONFLICT(HttpStatus.CONFLICT, "이미 동일한 관리자 역할이 활성 상태입니다."),
    ADMIN_TARGET_USER_NOT_FOUND(HttpStatus.NOT_FOUND, "관리자 역할 대상 사용자를 찾을 수 없습니다."),
    POST_NOT_FOUND(HttpStatus.NOT_FOUND, "게시글을 찾을 수 없습니다."),
    PLACE_NOT_FOUND(HttpStatus.NOT_FOUND, "장소를 찾을 수 없습니다."),
    PLACE_DUPLICATE_NOT_FOUND(HttpStatus.NOT_FOUND, "중복 후보 장소를 찾을 수 없습니다."),
    PLACE_MERGE_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "장소 병합 요청이 올바르지 않습니다."),
    PLACE_DUPLICATE_CANDIDATE_NOT_FOUND(HttpStatus.NOT_FOUND, "중복 장소 후보를 찾을 수 없습니다."),
    PLACE_DUPLICATE_DECISION_ALREADY_COMPLETED(HttpStatus.CONFLICT, "이미 판정이 완료된 중복 장소 후보입니다."),
    PLACE_OPERATING_STATUS_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "장소 운영 상태 요청이 올바르지 않습니다."),
    PLACE_DISCOVERY_STATUS_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "장소 탐색 노출 상태 요청이 올바르지 않습니다."),
    PLACE_INFORMATION_EVIDENCE_NOT_FOUND(HttpStatus.NOT_FOUND, "장소 정보 증빙을 찾을 수 없습니다."),
    PLACE_INFORMATION_VERIFICATION_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "장소 정보 검증 요청이 올바르지 않습니다."),
    PLACE_INFORMATION_REPORT_NOT_FOUND(HttpStatus.NOT_FOUND, "장소 정보 신고를 찾을 수 없습니다."),
    PLACE_INFORMATION_REPORT_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "장소 정보 신고 요청이 올바르지 않습니다."),
    PLACE_INFORMATION_REPORT_ALREADY_SUBMITTED(HttpStatus.CONFLICT, "이미 처리 대기 중인 장소 정보 신고가 있습니다."),
    PLACE_INFORMATION_DISPUTE_NOT_FOUND(HttpStatus.NOT_FOUND, "장소 정보 반박을 찾을 수 없습니다."),
    PLACE_INFORMATION_DISPUTE_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "장소 정보 반박 요청이 올바르지 않습니다."),
    PLACE_OPERATING_SCHEDULE_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "장소 영업시간 일정 요청이 올바르지 않습니다."),
    PLACE_EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "이벤트를 찾을 수 없습니다."),
    PLACE_EVENT_INVALID_PERIOD(HttpStatus.BAD_REQUEST, "이벤트 종료 시각은 시작 시각보다 이후여야 합니다."),
    PLACE_EVENT_UPDATE_NOT_ALLOWED(HttpStatus.CONFLICT, "공개되었거나 취소된 이벤트는 수정할 수 없습니다."),
    PLACE_EVENT_PUBLISH_NOT_ALLOWED(HttpStatus.CONFLICT, "초안 상태의 종료되지 않은 이벤트만 공개할 수 있습니다."),
    PLACE_EVENT_CANCEL_NOT_ALLOWED(HttpStatus.CONFLICT, "이미 취소된 이벤트입니다."),
    PLACE_EVENT_CONNECTED(HttpStatus.CONFLICT, "연결된 기간형 이벤트가 있어 장소를 삭제하거나 병합할 수 없습니다."),
    PLACE_CHECK_IN_CONNECTED(HttpStatus.CONFLICT, "연결된 체크인 이력이 있어 장소를 삭제하거나 병합할 수 없습니다."),
    PLACE_SCOUT_FIELD_REPORT_CONNECTED(HttpStatus.CONFLICT, "연결된 Scout 현장 제보가 있어 장소를 삭제하거나 병합할 수 없습니다."),
    PLACE_MERGE_NOT_ALLOWED(HttpStatus.CONFLICT, "중복 장소로 확인되지 않아 병합할 수 없습니다."),
    PLACE_MERGE_RELATED_DATA_CONNECTED(HttpStatus.CONFLICT, "지원하지 않는 장소 연관 데이터가 있어 병합할 수 없습니다."),
    PLACE_MERGE_HISTORY_NOT_FOUND(HttpStatus.NOT_FOUND, "장소 병합 이력을 찾을 수 없습니다."),
    PLACE_MERGE_ALREADY_RESTORED(HttpStatus.CONFLICT, "이미 복구된 장소 병합 이력입니다."),
    PLACE_MERGE_RESTORE_NOT_ALLOWED(HttpStatus.CONFLICT, "현재 장소 상태로는 병합 복구를 진행할 수 없습니다."),
    PLACE_KAKAO_PLACE_ID_CONFLICT(HttpStatus.CONFLICT, "이미 다른 장소에 연결된 Kakao place id입니다."),
    RECOMMENDATION_EXPLANATION_NOT_FOUND(HttpStatus.NOT_FOUND, "추천 설명 정보를 찾을 수 없습니다."),
    RECOMMENDATION_TRAFFIC_POLICY_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "추천 트래픽 정책 요청이 올바르지 않습니다."),
    RECOMMENDATION_TRAFFIC_POLICY_VERSION_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 추천 버전입니다."),
    RECOMMENDATION_TRAFFIC_POLICY_TOTAL_INVALID(HttpStatus.BAD_REQUEST, "추천 트래픽 비율 합계는 100이어야 합니다."),
    RECOMMENDATION_METRIC_QUERY_TOO_LARGE(HttpStatus.BAD_REQUEST, "추천 성과 조회 대상 장소가 너무 많습니다. 검색어 또는 기간 조건을 좁혀주세요."),
    TRUST_SCORE_ANOMALY_NOT_FOUND(HttpStatus.NOT_FOUND, "Trust Score 이상치를 찾을 수 없습니다."),
    TRUST_SCORE_REPORTER_POLICY_NOT_FOUND(HttpStatus.NOT_FOUND, "신고자 Trust Score 정책을 찾을 수 없습니다."),
    TRUST_SCORE_INTERVENTION_RULE_NOT_FOUND(HttpStatus.NOT_FOUND, "Trust Score 개입 규칙을 찾을 수 없습니다."),
    TRUST_SCORE_INTERVENTION_RULE_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "Trust Score 개입 규칙 요청이 올바르지 않습니다."),
    TRUST_SCORE_INTERVENTION_RULE_DUPLICATED(HttpStatus.CONFLICT, "이미 존재하는 Trust Score 개입 규칙 이름입니다."),
    AD_NOT_FOUND(HttpStatus.NOT_FOUND, "이벤트/광고를 찾을 수 없습니다."),
    AD_INVALID_PERIOD(HttpStatus.BAD_REQUEST, "이벤트/광고 종료 시각은 시작 시각보다 이후여야 합니다."),
    UNSUPPORTED_PLACE_SORT_PARAM(HttpStatus.BAD_REQUEST, "장소 목록은 LATEST, OLDEST, LEVEL_DESC 정렬만 지원합니다."),
    REPORT_NOT_FOUND(HttpStatus.NOT_FOUND, "신고 내역을 찾을 수 없습니다."),
    REPORT_ALREADY_PROCESSED(HttpStatus.CONFLICT, "이미 처리된 신고입니다."),
    APPEAL_NOT_FOUND(HttpStatus.NOT_FOUND, "이의제기 내역을 찾을 수 없습니다."),
    APPEAL_ALREADY_PROCESSED(HttpStatus.CONFLICT, "이미 처리된 이의제기입니다."),
    USER_NOT_BANNED(HttpStatus.CONFLICT, "제재 중인 사용자가 아닙니다."),
    INVALID_SANCTION_PERIOD(HttpStatus.BAD_REQUEST, "제재 종료 시각 또는 기간이 올바르지 않습니다."),
    INVALID_SANCTION_FILTER_PERIOD(HttpStatus.BAD_REQUEST, "제재 이력 조회 종료 시각은 시작 시각보다 이후여야 합니다."),
    INVALID_AUDIT_LOG_FILTER_PERIOD(HttpStatus.BAD_REQUEST, "감사 로그 조회 종료 시각은 시작 시각보다 이후여야 합니다."),
    INVALID_NOTIFICATION_FILTER_PERIOD(HttpStatus.BAD_REQUEST, "알림 조회 종료 시각은 시작 시각보다 이후여야 합니다."),
    INVALID_NOTIFICATION_DELIVERY_FILTER_PERIOD(HttpStatus.BAD_REQUEST, "알림 발송 결과 조회 종료 시각은 시작 시각보다 이후여야 합니다."),
    INVALID_OUTBOX_EVENT_FILTER_PERIOD(HttpStatus.BAD_REQUEST, "Outbox 이벤트 조회 종료 시각은 시작 시각보다 이후여야 합니다."),
    OUTBOX_EVENT_RETRY_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "Outbox 이벤트 재처리 사유가 필요합니다."),
    OUTBOX_EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Outbox 이벤트를 찾을 수 없습니다."),
    OUTBOX_EVENT_RETRY_NOT_ALLOWED(HttpStatus.CONFLICT, "최종 실패 상태의 Outbox 이벤트만 재처리할 수 있습니다."),
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "알림을 찾을 수 없습니다."),
    PENDING_REPORT_NOT_FOUND(HttpStatus.CONFLICT, "처리할 대기 신고가 없습니다."),
    AUDIT_LOG_WRITE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "감사 로그 저장에 실패했습니다."),
    RECOMMENDATION_POLICY_HISTORY_WRITE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "추천 정책 변경 이력 저장에 실패했습니다."),
    POST_DELETE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "게시글 삭제에 실패했습니다."),
    S3_NOT_CONFIGURED(HttpStatus.INTERNAL_SERVER_ERROR, "S3 설정이 누락되었습니다."),
    S3_CONNECTION_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "S3 연결에 실패했습니다."),
    S3_REPORT_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "S3 객체 리포트 생성에 실패했습니다.");

    private final HttpStatus status;
    private final String message;
}
