spring:
  docker:
    compose:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls-primary-name: web
    urls:
      - name: app
        url: /v3/api-docs/app
      - name: web
        url: /v3/api-docs/web

seed:
  admin:
    username: ${SEED_ADMIN_USERNAME:admin}
    name: ${SEED_ADMIN_NAME:관리자}
    email: ${SEED_ADMIN_EMAIL:admin@local}
    password: ${SEED_ADMIN_PASSWORD:admin1234!}
