spring:
  application:
    name: Pingdom
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pingdom}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DB_USERNAME:pingdom}
    password: ${DB_PASSWORD:pingdom}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET:}
      region:
        static: ${AWS_REGION:ap-northeast-2}
      stack:
        auto: false
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
  config:
    import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS}
  refresh-token-expiration-seconds: ${JWT_REFRESH_TOKEN_EXPIRATION_SECONDS}

postmark:
  server-token: ${POSTMARK_SERVER_TOKEN}
  from-email: ${MAIL_FROM}
  verification-base-url: ${MAIL_VERIFICATION_BASE_URL}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
