package com.typenull.pingdom.moderation.domain.audit;

public enum AdminAuditTargetType {
    USER,
    REPORT,
    APPEAL,
    POST,
    PLACE,
    PLACE_INFORMATION_EVIDENCE,
    PLACE_INFORMATION_REPORT,
    PLACE_INFORMATION_DISPUTE,
    VISITOR_VERIFICATION_REPORT,
    VISITOR_VERIFICATION_REPORT_CORRECTION,
    PLACE_OPERATING_NOTICE,
    PLACE_EVENT,
    TRUST_SCORE_ANOMALY,
    TRUST_SCORE_INTERVENTION_RULE,
    MERCHANT_OWNER,
    MERCHANT_VERIFICATION,
    MERCHANT_PLACE_CLAIM,
    AD
}
