ALTER TABLE mcp_spatial_raw_data
    DROP CONSTRAINT mcp_spatial_raw_data_pkey;

ALTER TABLE mcp_spatial_raw_data
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

UPDATE mcp_spatial_raw_data
SET id = DEFAULT
WHERE id IS NULL;

ALTER TABLE mcp_spatial_raw_data
    ALTER COLUMN id SET NOT NULL,
    ADD CONSTRAINT pk_mcp_spatial_raw_data PRIMARY KEY (id),
    ADD COLUMN observed_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX idx_mcp_spatial_raw_data_account_observed_at
    ON mcp_spatial_raw_data (account_id, observed_at DESC);

CREATE INDEX idx_mcp_spatial_raw_data_observed_at
    ON mcp_spatial_raw_data (observed_at);
