ALTER TABLE map_image
    ADD COLUMN IF NOT EXISTS visibility_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE map_image
    ADD COLUMN IF NOT EXISTS hidden_at TIMESTAMP(6);

ALTER TABLE map_image
    ADD COLUMN IF NOT EXISTS hidden_reason VARCHAR(500);

ALTER TABLE map_image
    ADD COLUMN IF NOT EXISTS restored_at TIMESTAMP(6);

ALTER TABLE map_image
    ADD COLUMN IF NOT EXISTS restored_reason VARCHAR(500);

ALTER TABLE map_image
    ADD COLUMN IF NOT EXISTS visibility_updated_by BIGINT;

CREATE INDEX IF NOT EXISTS idx_map_image_visibility_created
    ON map_image (visibility_status, created_time DESC, map_image_id DESC);

CREATE TABLE IF NOT EXISTS reporter_moderation_policy (
    reporter_user_id BIGINT PRIMARY KEY,
    reporter_username VARCHAR(50) NOT NULL,
    submitted_count BIGINT NOT NULL DEFAULT 0,
    accepted_count BIGINT NOT NULL DEFAULT 0,
    declined_count BIGINT NOT NULL DEFAULT 0,
    false_report_count BIGINT NOT NULL DEFAULT 0,
    trust_score INTEGER NOT NULL DEFAULT 100,
    restricted_until TIMESTAMP(6),
    restriction_reason VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reporter_moderation_policy_restricted
    ON reporter_moderation_policy (restricted_until);

CREATE TABLE IF NOT EXISTS report_appeal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    appellant_user_id BIGINT NOT NULL,
    appellant_username VARCHAR(50) NOT NULL,
    target_user_id BIGINT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    admin_user_id BIGINT,
    admin_reason VARCHAR(500),
    processed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_report_appeal_report FOREIGN KEY (report_id) REFERENCES post_report (id)
);

CREATE INDEX IF NOT EXISTS idx_report_appeal_status_created
    ON report_appeal (status, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_report_appeal_report_appellant_status
    ON report_appeal (report_id, appellant_user_id, status);
