ALTER TABLE location_check_in DROP CONSTRAINT uq_location_check_in_daily;
ALTER TABLE location_check_in DROP CONSTRAINT ck_location_check_in_status;

ALTER TABLE location_check_in
    ADD CONSTRAINT ck_location_check_in_status
        CHECK (status IN ('PROXIMITY_MATCHED', 'DWELL_VERIFIED'));

CREATE UNIQUE INDEX uq_location_check_in_daily
    ON location_check_in (tourist_user_id, place_id, check_in_date)
    WHERE status = 'PROXIMITY_MATCHED';

CREATE UNIQUE INDEX uq_location_check_in_dwell_daily
    ON location_check_in (tourist_user_id, place_id, check_in_date)
    WHERE status = 'DWELL_VERIFIED';

CREATE TABLE visit_verification_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tourist_user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    place_id BIGINT NOT NULL REFERENCES map_place (map_place_id) ON DELETE RESTRICT,
    verification_date DATE NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_observed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_verified_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_distance_meters DOUBLE PRECISION NOT NULL,
    required_radius_meters DOUBLE PRECISION NOT NULL,
    required_dwell_seconds BIGINT NOT NULL,
    verified_dwell_seconds BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    completed_check_in_id BIGINT REFERENCES location_check_in (id) ON DELETE RESTRICT,
    CONSTRAINT ck_visit_verification_session_distance CHECK (last_distance_meters >= 0 AND last_distance_meters <= 1000),
    CONSTRAINT ck_visit_verification_session_radius CHECK (required_radius_meters >= 10 AND required_radius_meters <= 20),
    CONSTRAINT ck_visit_verification_session_duration CHECK (required_dwell_seconds > 0 AND verified_dwell_seconds >= 0),
    CONSTRAINT ck_visit_verification_session_status CHECK (status IN (
        'STARTED', 'IN_PROGRESS', 'PROXIMITY_LOST', 'COMPLETED', 'EXPIRED', 'REJECTED'
    )),
    CONSTRAINT ck_visit_verification_session_completed CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL AND completed_check_in_id IS NOT NULL)
        OR (status <> 'COMPLETED' AND completed_at IS NULL AND completed_check_in_id IS NULL)
    )
);

CREATE UNIQUE INDEX uq_visit_verification_session_active
    ON visit_verification_session (tourist_user_id, place_id, verification_date)
    WHERE status IN ('STARTED', 'IN_PROGRESS');

CREATE UNIQUE INDEX uq_visit_verification_session_completed_check_in
    ON visit_verification_session (completed_check_in_id)
    WHERE completed_check_in_id IS NOT NULL;

CREATE INDEX idx_visit_verification_session_retention
    ON visit_verification_session (expires_at);
