CREATE TABLE map_bookmark_trend_tracking (
    id BOOLEAN PRIMARY KEY DEFAULT TRUE,
    started_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_map_bookmark_trend_tracking_singleton CHECK (id = TRUE)
);

INSERT INTO map_bookmark_trend_tracking (id, started_at)
VALUES (TRUE, CURRENT_TIMESTAMP);

CREATE TABLE map_bookmark_trend_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL REFERENCES map_place (map_place_id) ON DELETE RESTRICT,
    origin_place_id BIGINT NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_map_bookmark_trend_event_type
        CHECK (event_type IN ('BASELINE_ACTIVE', 'ADDED', 'REMOVED'))
);

INSERT INTO map_bookmark_trend_event (
    user_id,
    place_id,
    origin_place_id,
    event_type,
    occurred_at
)
SELECT
    bookmark.user_id,
    bookmark.place_id,
    bookmark.place_id,
    'BASELINE_ACTIVE',
    tracking.started_at - INTERVAL '1 microsecond'
FROM map_bookmark bookmark
JOIN map_place place ON place.map_place_id = bookmark.place_id
CROSS JOIN map_bookmark_trend_tracking tracking
WHERE tracking.id = TRUE;

CREATE INDEX idx_map_bookmark_trend_event_stream
    ON map_bookmark_trend_event (user_id, origin_place_id, occurred_at DESC, id DESC);

CREATE INDEX idx_map_bookmark_trend_event_place_time
    ON map_bookmark_trend_event (place_id, occurred_at DESC, user_id, id DESC);
