CREATE TABLE merchant_place_media_upload (
    merchant_place_media_upload_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    issued_by_user_id BIGINT NOT NULL,
    s3_key VARCHAR(500) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    registered_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_merchant_place_media_upload_s3_key UNIQUE (s3_key),
    CONSTRAINT fk_merchant_place_media_upload_place FOREIGN KEY (place_id)
        REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT fk_merchant_place_media_upload_issuer FOREIGN KEY (issued_by_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_merchant_place_media_upload_status CHECK (status IN ('ISSUED', 'REGISTERED')),
    CONSTRAINT ck_merchant_place_media_upload_registered_at CHECK (
        (status = 'ISSUED' AND registered_at IS NULL)
        OR (status = 'REGISTERED' AND registered_at IS NOT NULL)
    )
);

CREATE INDEX idx_merchant_place_media_upload_expiration
    ON merchant_place_media_upload (status, expires_at);
