ALTER TABLE reservation
    ADD COLUMN reviewed_by BIGINT,
    ADD COLUMN reviewed_at TIMESTAMP(6),
    ADD COLUMN review_reason VARCHAR(500),
    ADD COLUMN rejected_at TIMESTAMP(6),
    ADD COLUMN canceled_by BIGINT;

ALTER TABLE reservation DROP CONSTRAINT ck_reservation_status;
ALTER TABLE reservation ADD CONSTRAINT ck_reservation_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'));
ALTER TABLE reservation DROP CONSTRAINT ck_reservation_state_times;
ALTER TABLE reservation ADD CONSTRAINT ck_reservation_state_times CHECK (
    (status = 'PENDING' AND confirmed_at IS NULL AND rejected_at IS NULL AND canceled_at IS NULL)
    OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND rejected_at IS NULL AND canceled_at IS NULL)
    OR (status = 'REJECTED' AND confirmed_at IS NULL AND rejected_at IS NOT NULL AND canceled_at IS NULL)
    OR (status = 'CANCELED' AND confirmed_at IS NOT NULL AND rejected_at IS NULL AND canceled_at IS NOT NULL)
);

CREATE TABLE reservation_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservation(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    changed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reason VARCHAR(500),
    changed_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_reservation_status_history_reservation ON reservation_status_history(reservation_id, changed_at, id);
