ALTER TABLE community_post
    ADD COLUMN category_id VARCHAR(30) NOT NULL,
    ADD COLUMN title VARCHAR(50) NOT NULL,
    ADD COLUMN content VARCHAR(5000) NOT NULL,
    ADD COLUMN user_id BIGINT NOT NULL,
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
