CREATE TABLE IF NOT EXISTS admin_place_merge_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_place_id BIGINT NOT NULL,
    target_place_id BIGINT NOT NULL,
    admin_user_id BIGINT,
    source_place_snapshot TEXT NOT NULL,
    target_place_snapshot TEXT NOT NULL,
    moved_image_ids TEXT NOT NULL,
    moved_bookmark_ids TEXT NOT NULL,
    deleted_bookmarks TEXT NOT NULL,
    moved_conversion_ids TEXT NOT NULL,
    deleted_conversions TEXT NOT NULL,
    moved_click_ids TEXT NOT NULL,
    moved_exposure_ids TEXT NOT NULL,
    moved_feature_log_ids TEXT NOT NULL,
    restored BOOLEAN NOT NULL DEFAULT FALSE,
    restored_at TIMESTAMP(6),
    merged_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_admin_place_merge_history_created
    ON admin_place_merge_history (merged_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_admin_place_merge_history_source
    ON admin_place_merge_history (source_place_id);

CREATE INDEX IF NOT EXISTS idx_admin_place_merge_history_target
    ON admin_place_merge_history (target_place_id);
