CREATE TABLE voice_ai_session (
    session_id VARCHAR(36) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_voice_ai_session_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_voice_ai_session_status CHECK (status IN ('ACTIVE', 'CLOSED'))
);

CREATE INDEX idx_voice_ai_session_user_id ON voice_ai_session(user_id);

CREATE TABLE voice_ai_replay (
    voice_ai_replay_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    envelope JSONB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_voice_ai_replay_session FOREIGN KEY (session_id)
        REFERENCES voice_ai_session (session_id) ON DELETE CASCADE,
    CONSTRAINT uq_voice_ai_replay_session_request UNIQUE (session_id, request_id)
);
