ALTER TABLE community_post ADD COLUMN country_code varchar(2), ADD COLUMN region varchar(100), ADD COLUMN view_count bigint NOT NULL DEFAULT 0;
ALTER TABLE community_post ADD CONSTRAINT ck_community_post_view_count CHECK (view_count >= 0);
CREATE INDEX idx_community_post_country_created ON community_post(country_code, created_at DESC, community_post_id DESC) WHERE hidden = false;
ALTER TABLE community_post_comment ADD COLUMN parent_comment_id bigint REFERENCES community_post_comment(community_post_comment_id);
CREATE INDEX idx_community_comment_parent ON community_post_comment(parent_comment_id);
CREATE TABLE community_comment_like (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL REFERENCES community_post_comment(community_post_comment_id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(comment_id, user_id)
);
CREATE TABLE community_post_image (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    post_id bigint REFERENCES community_post(community_post_id),
    s3_key varchar(500) NOT NULL UNIQUE,
    image_url varchar(2048),
    position integer,
    expires_at timestamp NOT NULL,
    UNIQUE(post_id, position),
    CHECK ((post_id IS NULL AND position IS NULL) OR (post_id IS NOT NULL AND position BETWEEN 0 AND 9 AND image_url IS NOT NULL))
);
CREATE INDEX idx_community_image_pending_expiry ON community_post_image(expires_at) WHERE post_id IS NULL;
