CREATE TABLE IF NOT EXISTS notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    new_hotplace_enabled BOOLEAN DEFAULT TRUE NOT NULL,
    new_like_enabled BOOLEAN DEFAULT TRUE NOT NULL,
    quiet_hours_enabled BOOLEAN DEFAULT FALSE NOT NULL,
    quiet_hours_start TIME,
    quiet_hours_end TIME,
    timezone VARCHAR(50) DEFAULT 'Asia/Seoul' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_notification_settings_user UNIQUE (user_id),
    CONSTRAINT fk_notification_settings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_notification_settings_quiet_hours
        CHECK (
            quiet_hours_enabled = FALSE
            OR (
                quiet_hours_start IS NOT NULL
                AND quiet_hours_end IS NOT NULL
                AND quiet_hours_start <> quiet_hours_end
            )
        )
);

INSERT INTO notification_settings (user_id, created_at, updated_at)
SELECT id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users
ON CONFLICT (user_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS fcm_device_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_registered_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_fcm_device_token_token UNIQUE (token),
    CONSTRAINT fk_fcm_device_token_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_fcm_device_token_user_updated
    ON fcm_device_token (user_id, updated_at DESC);

INSERT INTO fcm_device_token (user_id, token, created_at, updated_at, last_registered_at)
SELECT id, fcm_token, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users
WHERE fcm_token IS NOT NULL
  AND btrim(fcm_token) <> ''
ON CONFLICT (token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    updated_at = CURRENT_TIMESTAMP,
    last_registered_at = CURRENT_TIMESTAMP;

ALTER TABLE notifications
    ALTER COLUMN token DROP NOT NULL;
