CREATE TABLE admin_ad (
    admin_ad_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    redirect_url VARCHAR(500) NOT NULL,
    start_at TIMESTAMP(6) NOT NULL,
    end_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL,
    email_verification_code VARCHAR(20),
    email_verification_expires_at TIMESTAMP(6),
    password VARCHAR(255) NOT NULL,
    birth_year INTEGER NOT NULL,
    profile_image_url VARCHAR(2048),
    language VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    refresh_token VARCHAR(1000),
    role VARCHAR(20) NOT NULL,
    banned BOOLEAN NOT NULL,
    banned_at TIMESTAMP(6),
    ban_reason VARCHAR(255),
    fcm_token VARCHAR(255),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(20) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT uk_oauth_accounts_provider_provider_id UNIQUE (provider, provider_id),
    CONSTRAINT fk_oauth_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_oauth_accounts_provider_provider_id
    ON oauth_accounts (provider, provider_id);

CREATE TABLE map_place (
    map_place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    category VARCHAR(50),
    image_url VARCHAR(500),
    kakao_place_id VARCHAR(50),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    user_id BIGINT NOT NULL,
    photo_count BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE map_image (
    map_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(500) NOT NULL,
    s3_key VARCHAR(500) NOT NULL,
    title VARCHAR(100),
    description VARCHAR(1000),
    user_id BIGINT,
    username VARCHAR(255),
    created_time TIMESTAMP(6),
    like_count BIGINT NOT NULL,
    map_place_id BIGINT,
    CONSTRAINT fk_map_image_map_place FOREIGN KEY (map_place_id) REFERENCES map_place (map_place_id)
);

CREATE TABLE map_image_like (
    like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    map_image_id BIGINT,
    CONSTRAINT uk_map_image_like_user_image UNIQUE (user_id, map_image_id)
);

CREATE TABLE map_bookmark (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_map_bookmark_user_place UNIQUE (user_id, place_id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE post_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    reporter_username VARCHAR(50) NOT NULL,
    reported_image_id BIGINT NOT NULL,
    reported_user_id BIGINT NOT NULL,
    reported_image_url VARCHAR(500) NOT NULL,
    map_image_id BIGINT,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    processed_at TIMESTAMP(6),
    CONSTRAINT uk_post_report_user_image UNIQUE (reporter_user_id, map_image_id),
    CONSTRAINT fk_post_report_map_image FOREIGN KEY (map_image_id) REFERENCES map_image (map_image_id)
);

CREATE TABLE place_recommendation_click (
    place_recommendation_click_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    user_id BIGINT,
    recommendation_version VARCHAR(50) NOT NULL,
    request_id VARCHAR(50),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE place_recommendation_conversion (
    place_recommendation_conversion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_recommendation_click_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    conversion_type VARCHAR(20) NOT NULL,
    recommendation_version VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_place_recommendation_conversion_user_place_type
        UNIQUE (user_id, place_id, conversion_type)
);

CREATE TABLE place_recommendation_exposure (
    place_recommendation_exposure_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    user_id BIGINT,
    request_latitude DOUBLE PRECISION NOT NULL,
    request_longitude DOUBLE PRECISION NOT NULL,
    ranking INTEGER NOT NULL,
    recommendation_version VARCHAR(50) NOT NULL,
    request_id VARCHAR(50),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE place_recommendation_feature_log (
    place_recommendation_feature_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(50) NOT NULL,
    user_id BIGINT,
    place_id BIGINT NOT NULL,
    recommendation_version VARCHAR(50) NOT NULL,
    recommendation_stage VARCHAR(20) NOT NULL,
    candidate_source VARCHAR(20) NOT NULL,
    ranking INTEGER NOT NULL,
    distance_meters BIGINT NOT NULL,
    geo_score DOUBLE PRECISION NOT NULL,
    personal_score DOUBLE PRECISION NOT NULL,
    quality_score DOUBLE PRECISION NOT NULL,
    engagement_score DOUBLE PRECISION NOT NULL,
    conversion_score DOUBLE PRECISION NOT NULL,
    exploration_score DOUBLE PRECISION NOT NULL,
    freshness_score DOUBLE PRECISION NOT NULL,
    final_score DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE place_recommendation_snapshot (
    place_id BIGINT PRIMARY KEY,
    photo_count BIGINT NOT NULL,
    bookmark_count BIGINT NOT NULL,
    total_like_count BIGINT NOT NULL,
    click_count BIGINT NOT NULL,
    bookmark_conversion_count BIGINT NOT NULL,
    like_conversion_count BIGINT NOT NULL,
    exposure_count BIGINT NOT NULL,
    latest_post_created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE place_recommendation_version_snapshot (
    place_recommendation_version_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    recommendation_version VARCHAR(50) NOT NULL,
    click_count BIGINT NOT NULL,
    bookmark_conversion_count BIGINT NOT NULL,
    like_conversion_count BIGINT NOT NULL,
    exposure_count BIGINT NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_place_recommendation_version_snapshot_place_version
        UNIQUE (place_id, recommendation_version)
);

CREATE TABLE place_similarity_snapshot (
    place_similarity_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    left_place_id BIGINT NOT NULL,
    right_place_id BIGINT NOT NULL,
    geo_kernel_score DOUBLE PRECISION NOT NULL,
    co_bookmark_pmi_score DOUBLE PRECISION NOT NULL,
    co_like_cosine_score DOUBLE PRECISION NOT NULL,
    trend_similarity_score DOUBLE PRECISION NOT NULL,
    total_similarity_score DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_place_similarity_snapshot_pair UNIQUE (left_place_id, right_place_id)
);
