CREATE TABLE IF NOT EXISTS notification_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    user_id BIGINT,
    notification_id BIGINT,
    notification_type VARCHAR(50),
    outbox_event_id VARCHAR(36),
    outbox_event_type VARCHAR(50),
    recipient_hash VARCHAR(64),
    provider_message_id VARCHAR(200),
    provider_error_code VARCHAR(100),
    error_code VARCHAR(80),
    failure_reason VARCHAR(1000),
    retryable BOOLEAN DEFAULT FALSE NOT NULL,
    attempt_count INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_notification_delivery_outbox_channel_recipient
        UNIQUE (outbox_event_id, channel, recipient_hash)
);

CREATE INDEX IF NOT EXISTS idx_notification_delivery_user_created
    ON notification_delivery (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_notification_delivery_channel_status_created
    ON notification_delivery (channel, status, created_at);

CREATE INDEX IF NOT EXISTS idx_notification_delivery_outbox_event
    ON notification_delivery (outbox_event_id);
