CREATE TABLE privacy_processing_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_user_id BIGINT,
    actor_user_id BIGINT,
    actor_type VARCHAR(20) NOT NULL,
    action VARCHAR(50) NOT NULL,
    details TEXT,
    request_id VARCHAR(100),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_privacy_processing_history_created
    ON privacy_processing_history (created_at DESC, id DESC);

CREATE INDEX idx_privacy_processing_history_subject_created
    ON privacy_processing_history (subject_user_id, created_at DESC);

CREATE INDEX idx_privacy_processing_history_action_created
    ON privacy_processing_history (action, created_at DESC);

CREATE INDEX idx_privacy_processing_history_actor_created
    ON privacy_processing_history (actor_user_id, created_at DESC);
