CREATE TABLE map_place_regular_operating_hour (
    map_place_id BIGINT NOT NULL,
    day_of_week VARCHAR(9) NOT NULL,
    opens_at TIME NOT NULL,
    closes_at TIME NOT NULL,
    CONSTRAINT pk_map_place_regular_operating_hour
        PRIMARY KEY (map_place_id, day_of_week, opens_at, closes_at),
    CONSTRAINT fk_map_place_regular_operating_hour_place
        FOREIGN KEY (map_place_id) REFERENCES map_place (map_place_id) ON DELETE NO ACTION,
    CONSTRAINT ck_map_place_regular_operating_hour_day
        CHECK (day_of_week IN (
            'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
            'FRIDAY', 'SATURDAY', 'SUNDAY'
        )),
    CONSTRAINT ck_map_place_regular_operating_hour_range
        CHECK (opens_at <> closes_at)
);

CREATE TABLE map_place_operating_exception (
    operating_exception_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_place_id BIGINT NOT NULL,
    exception_date DATE NOT NULL,
    closed BOOLEAN NOT NULL,
    CONSTRAINT uk_map_place_operating_exception_date
        UNIQUE (map_place_id, exception_date),
    CONSTRAINT fk_map_place_operating_exception_place
        FOREIGN KEY (map_place_id) REFERENCES map_place (map_place_id) ON DELETE NO ACTION
);

CREATE TABLE map_place_operating_exception_hour (
    operating_exception_id BIGINT NOT NULL,
    opens_at TIME NOT NULL,
    closes_at TIME NOT NULL,
    CONSTRAINT pk_map_place_operating_exception_hour
        PRIMARY KEY (operating_exception_id, opens_at, closes_at),
    CONSTRAINT fk_map_place_operating_exception_hour_exception
        FOREIGN KEY (operating_exception_id)
            REFERENCES map_place_operating_exception (operating_exception_id) ON DELETE NO ACTION,
    CONSTRAINT ck_map_place_operating_exception_hour_range
        CHECK (opens_at <> closes_at)
);
