CREATE TABLE place_event (
    place_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_place_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    event_type VARCHAR(30) NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    publication_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_place_event_place
        FOREIGN KEY (map_place_id) REFERENCES map_place (map_place_id) ON DELETE NO ACTION,
    CONSTRAINT ck_place_event_type
        CHECK (event_type IN ('POP_UP', 'PERFORMANCE', 'EXHIBITION')),
    CONSTRAINT ck_place_event_publication_status
        CHECK (publication_status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),
    CONSTRAINT ck_place_event_period
        CHECK (end_at > start_at)
);

CREATE INDEX idx_place_event_place_id ON place_event (map_place_id);
CREATE INDEX idx_place_event_public_discovery
    ON place_event (publication_status, end_at, start_at);
