CREATE TABLE user_travel_schedule (
    user_travel_schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    state VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_travel_schedule_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_travel_schedule_period
        CHECK (end_date >= start_date),
    CONSTRAINT ck_user_travel_schedule_state
        CHECK (state IN ('SCHEDULED', 'CANCELLED'))
);

CREATE INDEX idx_user_travel_schedule_user_period
    ON user_travel_schedule (user_id, start_date, end_date);

CREATE TABLE user_current_activity_intent (
    user_current_activity_intent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    activity_intent VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_current_activity_intent_user UNIQUE (user_id),
    CONSTRAINT fk_user_current_activity_intent_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_current_activity_intent_value
        CHECK (activity_intent IN (
            'EXPLORE',
            'EAT',
            'CAFE',
            'SHOP',
            'ATTEND_EVENT',
            'NIGHTLIFE'
        ))
);

CREATE INDEX idx_user_current_activity_intent_expires_at
    ON user_current_activity_intent (expires_at);
