CREATE TABLE merchant_place_claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_owner_user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    claim_reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    review_reason VARCHAR(500),
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_merchant_place_claim_profile
        FOREIGN KEY (merchant_owner_user_id) REFERENCES merchant_owner_profile (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_merchant_place_claim_place
        FOREIGN KEY (place_id) REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT fk_merchant_place_claim_reviewer
        FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_merchant_place_claim_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE INDEX idx_merchant_place_claim_owner_created
    ON merchant_place_claim (merchant_owner_user_id, created_at DESC, id DESC);

CREATE INDEX idx_merchant_place_claim_status_created
    ON merchant_place_claim (status, created_at DESC, id DESC);

CREATE UNIQUE INDEX uq_merchant_place_claim_pending_place
    ON merchant_place_claim (place_id)
    WHERE status = 'PENDING';
