CREATE TABLE tourist_offer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_owner_user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    benefit_description VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    starts_at TIMESTAMP(6) NOT NULL,
    ends_at TIMESTAMP(6) NOT NULL,
    total_quantity INTEGER NOT NULL,
    issued_quantity INTEGER NOT NULL DEFAULT 0,
    coupon_validity_days INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_tourist_offer_merchant_owner
        FOREIGN KEY (merchant_owner_user_id) REFERENCES merchant_owner_profile (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_tourist_offer_place
        FOREIGN KEY (place_id) REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT ck_tourist_offer_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'CLOSED')),
    CONSTRAINT ck_tourist_offer_period
        CHECK (ends_at > starts_at),
    CONSTRAINT ck_tourist_offer_quantity
        CHECK (total_quantity > 0 AND issued_quantity >= 0 AND issued_quantity <= total_quantity),
    CONSTRAINT ck_tourist_offer_coupon_validity_days
        CHECK (coupon_validity_days BETWEEN 1 AND 365)
);

CREATE INDEX idx_tourist_offer_public_period
    ON tourist_offer (status, starts_at, ends_at, id DESC);

CREATE INDEX idx_tourist_offer_place_public_period
    ON tourist_offer (place_id, status, starts_at, ends_at, id DESC);

CREATE INDEX idx_tourist_offer_merchant_created
    ON tourist_offer (merchant_owner_user_id, created_at DESC, id DESC);

CREATE TABLE tourist_coupon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    code VARCHAR(36) NOT NULL,
    status VARCHAR(20) NOT NULL,
    issued_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    redeemed_at TIMESTAMP(6),
    redeemed_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_tourist_coupon_offer
        FOREIGN KEY (offer_id) REFERENCES tourist_offer (id) ON DELETE CASCADE,
    CONSTRAINT fk_tourist_coupon_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_tourist_coupon_redeemer
        FOREIGN KEY (redeemed_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT uq_tourist_coupon_offer_user UNIQUE (offer_id, user_id),
    CONSTRAINT uq_tourist_coupon_code UNIQUE (code),
    CONSTRAINT ck_tourist_coupon_status
        CHECK (status IN ('ISSUED', 'REDEEMED')),
    CONSTRAINT ck_tourist_coupon_period
        CHECK (expires_at > issued_at),
    CONSTRAINT ck_tourist_coupon_redemption
        CHECK (
            (status = 'ISSUED' AND redeemed_at IS NULL AND redeemed_by IS NULL)
            OR (status = 'REDEEMED' AND redeemed_at IS NOT NULL)
        )
);

CREATE INDEX idx_tourist_coupon_user_issued
    ON tourist_coupon (user_id, issued_at DESC, id DESC);

CREATE INDEX idx_tourist_coupon_offer_status
    ON tourist_coupon (offer_id, status, id);
