CREATE TABLE place_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_owner_user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    starts_at TIMESTAMP(6) NOT NULL,
    ends_at TIMESTAMP(6) NOT NULL,
    total_capacity INTEGER NOT NULL,
    remaining_capacity INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_place_availability_merchant_owner FOREIGN KEY (merchant_owner_user_id)
        REFERENCES merchant_owner_profile (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_place_availability_place FOREIGN KEY (place_id)
        REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT ck_place_availability_period CHECK (ends_at > starts_at),
    CONSTRAINT ck_place_availability_capacity CHECK (
        total_capacity > 0 AND remaining_capacity >= 0 AND remaining_capacity <= total_capacity
    ),
    CONSTRAINT ck_place_availability_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT uq_place_availability_owner_slot UNIQUE (merchant_owner_user_id, place_id, starts_at, ends_at)
);

CREATE INDEX idx_place_availability_public
    ON place_availability (place_id, status, starts_at, ends_at, id);

CREATE INDEX idx_place_availability_owner
    ON place_availability (merchant_owner_user_id, starts_at, id);
