CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tourist_user_id BIGINT NOT NULL,
    availability_id BIGINT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    confirmed_at TIMESTAMP(6),
    canceled_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_reservation_tourist FOREIGN KEY (tourist_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reservation_availability FOREIGN KEY (availability_id)
        REFERENCES place_availability (id) ON DELETE RESTRICT,
    CONSTRAINT ck_reservation_quantity CHECK (quantity > 0),
    CONSTRAINT ck_reservation_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELED')),
    CONSTRAINT ck_reservation_state_times CHECK (
        (status = 'PENDING' AND confirmed_at IS NULL AND canceled_at IS NULL)
        OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND canceled_at IS NULL)
        OR (status = 'CANCELED' AND canceled_at IS NOT NULL)
    ),
    CONSTRAINT uq_reservation_tourist_idempotency UNIQUE (tourist_user_id, idempotency_key)
);

CREATE INDEX idx_reservation_tourist_created
    ON reservation (tourist_user_id, created_at DESC, id DESC);

CREATE INDEX idx_reservation_availability_status
    ON reservation (availability_id, status, created_at, id);
