CREATE TABLE trust_score_anomaly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    reporter_username VARCHAR(50) NOT NULL,
    anomaly_type VARCHAR(30) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    baseline_score INTEGER NOT NULL,
    observed_score INTEGER NOT NULL,
    submitted_count BIGINT NOT NULL,
    accepted_count BIGINT NOT NULL,
    declined_count BIGINT NOT NULL,
    false_report_count BIGINT NOT NULL,
    detected_at TIMESTAMP(6) NOT NULL,
    resolved_at TIMESTAMP(6),
    resolution_reason VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_trust_score_anomaly_reporter_policy
        FOREIGN KEY (reporter_user_id) REFERENCES reporter_moderation_policy (reporter_user_id) ON DELETE CASCADE,
    CONSTRAINT ck_trust_score_anomaly_type
        CHECK (anomaly_type IN ('RAPID_DROP', 'FALSE_REPORT_SPIKE', 'LOW_ACCEPTANCE_RATE', 'MANUAL_REVIEW')),
    CONSTRAINT ck_trust_score_anomaly_severity
        CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_trust_score_anomaly_score_range
        CHECK (baseline_score BETWEEN 0 AND 100 AND observed_score BETWEEN 0 AND 100),
    CONSTRAINT ck_trust_score_anomaly_counts
        CHECK (
            submitted_count >= 0
            AND accepted_count >= 0
            AND declined_count >= 0
            AND false_report_count >= 0
            AND accepted_count + declined_count <= submitted_count
            AND false_report_count <= declined_count
        ),
    CONSTRAINT ck_trust_score_anomaly_resolution
        CHECK (
            (resolved_at IS NULL AND resolution_reason IS NULL)
            OR (resolved_at IS NOT NULL)
        )
);

CREATE INDEX idx_trust_score_anomaly_reporter_detected
    ON trust_score_anomaly (reporter_user_id, detected_at DESC, id DESC);

CREATE INDEX idx_trust_score_anomaly_type_severity
    ON trust_score_anomaly (anomaly_type, severity, detected_at DESC);

CREATE INDEX idx_trust_score_anomaly_unresolved
    ON trust_score_anomaly (resolved_at, detected_at DESC);

CREATE TABLE trust_score_intervention_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(100) NOT NULL,
    trigger_type VARCHAR(30) NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    min_trust_score INTEGER NOT NULL,
    max_trust_score INTEGER NOT NULL,
    min_submitted_count BIGINT NOT NULL DEFAULT 0,
    min_false_report_count BIGINT NOT NULL DEFAULT 0,
    duration_days INTEGER,
    priority INTEGER NOT NULL DEFAULT 100,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_trust_score_intervention_rule_name UNIQUE (rule_name),
);
