CREATE TABLE reservable_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_owner_user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    product_type VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_reservable_product_merchant_owner FOREIGN KEY (merchant_owner_user_id)
        REFERENCES merchant_owner_profile (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_reservable_product_place FOREIGN KEY (place_id)
        REFERENCES map_place (map_place_id) ON DELETE RESTRICT,
    CONSTRAINT uq_reservable_product_id_type UNIQUE (id, product_type),
    CONSTRAINT ck_reservable_product_type CHECK (product_type IN ('TICKET', 'CLASS')),
    CONSTRAINT ck_reservable_product_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_reservable_product_owner
    ON reservable_product (merchant_owner_user_id, created_at DESC, id DESC);

CREATE INDEX idx_reservable_product_place_status
    ON reservable_product (place_id, status, product_type, id);

ALTER TABLE place_availability
    ADD COLUMN product_id BIGINT,
    ADD COLUMN product_type VARCHAR(20) DEFAULT 'GENERAL';

ALTER TABLE reservation
    ADD COLUMN product_id BIGINT,
    ADD COLUMN product_type VARCHAR(20) DEFAULT 'GENERAL';

ALTER TABLE place_availability
    ADD CONSTRAINT fk_place_availability_product FOREIGN KEY (product_id, product_type)
        REFERENCES reservable_product (id, product_type) ON DELETE RESTRICT NOT VALID,
    ADD CONSTRAINT ck_place_availability_product_type
        CHECK ((product_id IS NULL AND product_type = 'GENERAL')
            OR (product_id IS NOT NULL AND product_type IN ('TICKET', 'CLASS'))) NOT VALID;

ALTER TABLE reservation
    ADD CONSTRAINT fk_reservation_product FOREIGN KEY (product_id, product_type)
        REFERENCES reservable_product (id, product_type) ON DELETE RESTRICT NOT VALID,
    ADD CONSTRAINT ck_reservation_product_type
        CHECK ((product_id IS NULL AND product_type = 'GENERAL')
            OR (product_id IS NOT NULL AND product_type IN ('TICKET', 'CLASS'))) NOT VALID;

ALTER TABLE place_availability DROP CONSTRAINT uq_place_availability_owner_slot;
