CREATE TABLE visitor_verification_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    report_type VARCHAR(30) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    evidence_url VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    reviewer_admin_user_id BIGINT,
    review_note VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    reviewed_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_visitor_verification_report_reporter FOREIGN KEY (reporter_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_visitor_verification_report_place FOREIGN KEY (place_id)
        REFERENCES map_place (map_place_id) ON DELETE RESTRICT,
    CONSTRAINT fk_visitor_verification_report_reviewer FOREIGN KEY (reviewer_admin_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_visitor_verification_report_type CHECK (
        report_type IN ('PLACE_INFORMATION', 'OPERATING_HOURS', 'LOCATION', 'CLOSED_PLACE', 'OTHER')
    ),
    CONSTRAINT ck_visitor_verification_report_status CHECK (
        status IN ('SUBMITTED', 'ACCEPTED', 'REJECTED')
    ),
    CONSTRAINT ck_visitor_verification_report_review CHECK (
        (status = 'SUBMITTED' AND reviewer_admin_user_id IS NULL AND reviewed_at IS NULL AND review_note IS NULL)
        OR (status = 'ACCEPTED' AND reviewer_admin_user_id IS NOT NULL AND reviewed_at IS NOT NULL)
        OR (status = 'REJECTED' AND reviewer_admin_user_id IS NOT NULL
            AND reviewed_at IS NOT NULL AND review_note IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_visitor_verification_report_active
    ON visitor_verification_report (reporter_user_id, place_id, report_type)
    WHERE status = 'SUBMITTED';

CREATE INDEX idx_visitor_verification_report_reporter_created
    ON visitor_verification_report (reporter_user_id, created_at DESC, id DESC);

CREATE INDEX idx_visitor_verification_report_status_created
    ON visitor_verification_report (status, created_at, id);
