ALTER TABLE map_place
    ADD COLUMN primary_information_source VARCHAR(30) NOT NULL DEFAULT 'LEGACY',
    ADD COLUMN information_verification_status VARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED',
    ADD COLUMN information_verified_at TIMESTAMP(6),
    ADD COLUMN information_verified_by_admin_user_id BIGINT,
    ADD COLUMN information_evidence_updated_at TIMESTAMP(6);

ALTER TABLE map_place
    ADD CONSTRAINT ck_map_place_primary_information_source
        CHECK (primary_information_source IN (
            'LEGACY',
            'KAKAO',
            'MERCHANT_OWNER',
            'ADMIN',
            'USER_REPORT',
            'SYSTEM'
        )),
    ADD CONSTRAINT ck_map_place_information_verification_status
        CHECK (information_verification_status IN (
            'UNVERIFIED',
            'SOURCE_CONFIRMED',
            'OWNER_SUBMITTED',
            'ADMIN_VERIFIED',
            'REJECTED',
            'DISPUTED',
            'EXPIRED'
        )),
    ADD CONSTRAINT ck_map_place_information_admin_verified_metadata
        CHECK (
            information_verification_status <> 'ADMIN_VERIFIED'
            OR (
                information_verified_at IS NOT NULL
                AND information_verified_by_admin_user_id IS NOT NULL
            )
        );

CREATE TABLE place_information_evidence (
    place_information_evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_place_id BIGINT NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    evidence_type VARCHAR(30) NOT NULL,
    verification_status VARCHAR(30) NOT NULL,
    external_reference VARCHAR(100),
    reference_url VARCHAR(500),
    description VARCHAR(1000),
    submitted_by_user_id BIGINT,
    reviewed_by_admin_user_id BIGINT,
    review_reason VARCHAR(500),
    submitted_at TIMESTAMP(6) NOT NULL,
    reviewed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_place_information_evidence_place FOREIGN KEY (map_place_id)
        REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT ck_place_information_evidence_source_type CHECK (source_type IN (
        'LEGACY',
        'KAKAO',
        'MERCHANT_OWNER',
        'ADMIN',
        'USER_REPORT',
        'SYSTEM'
    )),
    CONSTRAINT ck_place_information_evidence_type CHECK (evidence_type IN (
        'EXTERNAL_PLACE_ID',
        'BUSINESS_CLAIM',
        'DOCUMENT',
        'PHOTO',
        'ADMIN_REVIEW',
        'USER_VISIT',
        'SYSTEM_SIGNAL'
    )),
    CONSTRAINT ck_place_information_evidence_status CHECK (verification_status IN (
        'UNVERIFIED',
        'SOURCE_CONFIRMED',
        'OWNER_SUBMITTED',
        'ADMIN_VERIFIED',
        'REJECTED',
        'DISPUTED',
        'EXPIRED'
    )),
    CONSTRAINT ck_place_information_evidence_payload CHECK (
        external_reference IS NOT NULL
        OR reference_url IS NOT NULL
        OR description IS NOT NULL
    ),
    CONSTRAINT ck_place_information_evidence_review CHECK (
        (
            verification_status = 'ADMIN_VERIFIED'
            AND reviewed_at IS NOT NULL
            AND reviewed_by_admin_user_id IS NOT NULL
        )
        OR (
            verification_status = 'REJECTED'
            AND reviewed_at IS NOT NULL
            AND reviewed_by_admin_user_id IS NOT NULL
            AND review_reason IS NOT NULL
        )
        OR verification_status NOT IN ('ADMIN_VERIFIED', 'REJECTED')
    )
);

CREATE INDEX idx_place_information_evidence_place_status
    ON place_information_evidence (map_place_id, verification_status, updated_at DESC, place_information_evidence_id DESC);

CREATE INDEX idx_place_information_evidence_source
    ON place_information_evidence (source_type, evidence_type, updated_at DESC, place_information_evidence_id DESC);

CREATE INDEX idx_map_place_information_verification
    ON map_place (information_verification_status, primary_information_source, map_place_id);
