CREATE TABLE location_check_in (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tourist_user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    check_in_date DATE NOT NULL,
    observed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    recorded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    distance_meters DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_location_check_in_tourist FOREIGN KEY (tourist_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_location_check_in_place FOREIGN KEY (place_id)
        REFERENCES map_place (map_place_id) ON DELETE RESTRICT,
    CONSTRAINT uq_location_check_in_daily UNIQUE (tourist_user_id, place_id, check_in_date),
    CONSTRAINT ck_location_check_in_status CHECK (status IN ('PROXIMITY_MATCHED')),
    CONSTRAINT ck_location_check_in_distance CHECK (distance_meters >= 0 AND distance_meters <= 1000)
);

CREATE INDEX idx_location_check_in_tourist_recorded
    ON location_check_in (tourist_user_id, recorded_at DESC, id DESC);

CREATE INDEX idx_location_check_in_place_recorded
    ON location_check_in (place_id, recorded_at DESC, id DESC);
