CREATE TABLE place_media (
    place_media_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_place_id BIGINT NOT NULL,
    purpose VARCHAR(20) NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    s3_key VARCHAR(500),
    thumbnail_url VARCHAR(500),
    thumbnail_s3_key VARCHAR(500),
    source_map_image_id BIGINT,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_place_media_place FOREIGN KEY (map_place_id)
        REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT fk_place_media_source_map_image FOREIGN KEY (source_map_image_id)
        REFERENCES map_image (map_image_id) ON DELETE CASCADE,
    CONSTRAINT ck_place_media_purpose CHECK (purpose IN ('VERIFICATION', 'EXPLORATION')),
    CONSTRAINT ck_place_media_image_url CHECK (length(trim(image_url)) > 0),
    CONSTRAINT ck_place_media_source CHECK (
        (
            purpose = 'VERIFICATION'
            AND source_map_image_id IS NOT NULL
        )
        OR (
            purpose = 'EXPLORATION'
            AND source_map_image_id IS NULL
        )
    ),
    CONSTRAINT ck_place_media_display_order CHECK (display_order >= 0)
);

CREATE UNIQUE INDEX uq_place_media_source_map_image
    ON place_media (source_map_image_id)
    WHERE source_map_image_id IS NOT NULL;

CREATE UNIQUE INDEX uq_place_media_primary_exploration
    ON place_media (map_place_id, purpose, display_order)
    WHERE purpose = 'EXPLORATION';

CREATE INDEX idx_place_media_place_purpose_order
    ON place_media (map_place_id, purpose, display_order, place_media_id);

INSERT INTO place_media (
    map_place_id,
    purpose,
    image_url,
    display_order,
    created_at,
    updated_at
)
SELECT
    map_place_id,
    'EXPLORATION',
    image_url,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM map_place
WHERE image_url IS NOT NULL
  AND length(trim(image_url)) > 0;

INSERT INTO place_media (
    map_place_id,
    purpose,
    image_url,
    s3_key,
    thumbnail_url,
    thumbnail_s3_key,
    source_map_image_id,
    display_order,
    created_at,
    updated_at
)
SELECT
    map_place_id,
    'VERIFICATION',
    image_url,
    s3_key,
    thumbnail_url,
    thumbnail_s3_key,
    map_image_id,
    0,
    COALESCE(created_time, CURRENT_TIMESTAMP),
    COALESCE(created_time, CURRENT_TIMESTAMP)
FROM map_image
WHERE map_place_id IS NOT NULL
  AND image_url IS NOT NULL
  AND length(trim(image_url)) > 0;
