CREATE TABLE visit_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_check_in_id BIGINT NOT NULL,
    tourist_user_id BIGINT NOT NULL,
    s3_key VARCHAR(512) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_visit_evidence_check_in FOREIGN KEY (location_check_in_id)
        REFERENCES location_check_in (id) ON DELETE CASCADE,
    CONSTRAINT fk_visit_evidence_tourist FOREIGN KEY (tourist_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT uq_visit_evidence_check_in UNIQUE (location_check_in_id),
    CONSTRAINT ck_visit_evidence_file_size CHECK (file_size > 0),
    CONSTRAINT ck_visit_evidence_expiration CHECK (expires_at > created_at)
);

CREATE INDEX idx_visit_evidence_tourist_created
    ON visit_evidence (tourist_user_id, created_at DESC, id DESC);

CREATE INDEX idx_visit_evidence_expires
    ON visit_evidence (expires_at, id);
