CREATE TABLE place_information_report (
    place_information_report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_place_id BIGINT NOT NULL,
    place_information_evidence_id BIGINT,
    reporter_user_id BIGINT NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    reason_type VARCHAR(30) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    evidence_url VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    reviewed_by_admin_user_id BIGINT,
    review_reason VARCHAR(500),
    reviewed_at TIMESTAMP(6),
    resolved_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_place_information_report_place FOREIGN KEY (map_place_id)
        REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT fk_place_information_report_evidence FOREIGN KEY (place_information_evidence_id)
        REFERENCES place_information_evidence (place_information_evidence_id) ON DELETE SET NULL,
    CONSTRAINT ck_place_information_report_target CHECK (target_type IN (
        'NAME',
        'ADDRESS',
        'GEOLOCATION',
        'OPERATING_STATUS',
        'TOURIST_INFORMATION',
        'SOURCE_EVIDENCE',
        'MEDIA',
        'OTHER'
    )),
    CONSTRAINT ck_place_information_report_reason CHECK (reason_type IN (
        'INCORRECT',
        'OUTDATED',
        'MISSING',
        'MISLEADING',
        'DUPLICATE',
        'CLOSED_OR_MOVED',
        'SPAM_OR_ABUSE',
        'OTHER'
    )),
    CONSTRAINT ck_place_information_report_status CHECK (status IN (
        'SUBMITTED',
        'UNDER_REVIEW',
        'ACCEPTED',
        'REJECTED',
        'DISPUTED',
        'RESOLVED',
        'CANCELED'
    )),
    CONSTRAINT ck_place_information_report_description CHECK (length(trim(description)) > 0),
    CONSTRAINT ck_place_information_report_review_metadata CHECK (
        (
            status IN ('SUBMITTED', 'CANCELED')
            AND reviewed_by_admin_user_id IS NULL
            AND reviewed_at IS NULL
            AND review_reason IS NULL
        )
        OR (
            status = 'UNDER_REVIEW'
            AND reviewed_by_admin_user_id IS NOT NULL
            AND reviewed_at IS NOT NULL
        )
        OR (
            status IN ('ACCEPTED', 'REJECTED', 'RESOLVED')
            AND reviewed_by_admin_user_id IS NOT NULL
            AND reviewed_at IS NOT NULL
            AND review_reason IS NOT NULL
        )
        OR (
            status = 'DISPUTED'
            AND reviewed_by_admin_user_id IS NOT NULL
            AND reviewed_at IS NOT NULL
        )
    ),
    CONSTRAINT ck_place_information_report_resolved_metadata CHECK (
        (
            status IN ('RESOLVED', 'CANCELED')
            AND resolved_at IS NOT NULL
        )
        OR (
            status NOT IN ('RESOLVED', 'CANCELED')
            AND resolved_at IS NULL
        )
    )
);

CREATE TABLE place_information_report_dispute (
    place_information_report_dispute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_information_report_id BIGINT NOT NULL,
    disputed_by_user_id BIGINT NOT NULL,
    description VARCHAR(1000) NOT NULL,
    evidence_url VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    reviewed_by_admin_user_id BIGINT,
    review_reason VARCHAR(500),
    reviewed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_place_information_report_dispute_report FOREIGN KEY (place_information_report_id)
        REFERENCES place_information_report (place_information_report_id) ON DELETE CASCADE,
    CONSTRAINT ck_place_information_report_dispute_status CHECK (status IN (
        'SUBMITTED',
        'ACCEPTED',
        'REJECTED'
    )),
    CONSTRAINT ck_place_information_report_dispute_description CHECK (length(trim(description)) > 0),
    CONSTRAINT ck_place_information_report_dispute_review CHECK (
        (
            status = 'SUBMITTED'
            AND reviewed_by_admin_user_id IS NULL
            AND reviewed_at IS NULL
            AND review_reason IS NULL
        )
        OR (
            status IN ('ACCEPTED', 'REJECTED')
            AND reviewed_by_admin_user_id IS NOT NULL
            AND reviewed_at IS NOT NULL
            AND review_reason IS NOT NULL
        )
    )
);

CREATE UNIQUE INDEX uq_place_information_report_active
    ON place_information_report (reporter_user_id, map_place_id, target_type)
    WHERE status IN ('SUBMITTED', 'UNDER_REVIEW', 'DISPUTED');

CREATE INDEX idx_place_information_report_place_status
    ON place_information_report (map_place_id, status, created_at DESC, place_information_report_id DESC);

CREATE INDEX idx_place_information_report_reporter_created
    ON place_information_report (reporter_user_id, created_at DESC, place_information_report_id DESC);

CREATE INDEX idx_place_information_report_status_created
    ON place_information_report (status, created_at DESC, place_information_report_id DESC);

CREATE INDEX idx_place_information_report_evidence
    ON place_information_report (place_information_evidence_id)
    WHERE place_information_evidence_id IS NOT NULL;

CREATE INDEX idx_place_information_report_dispute_report_status
    ON place_information_report_dispute (
        place_information_report_id,
        status,
        created_at DESC,
        place_information_report_dispute_id DESC
    );

CREATE INDEX idx_place_information_report_dispute_user_created
    ON place_information_report_dispute (
        disputed_by_user_id,
        created_at DESC,
        place_information_report_dispute_id DESC
    );
