CREATE TABLE visitor_verification_report_correction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    requester_user_id BIGINT NOT NULL,
    report_type VARCHAR(30) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    evidence_url VARCHAR(500),
    wait_time_minutes INTEGER,
    language_code VARCHAR(10),
    coupon_usage_status VARCHAR(20),
    crowd_level VARCHAR(20),
    status VARCHAR(20) NOT NULL,
    reviewer_admin_user_id BIGINT,
    review_note VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    reviewed_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_visitor_verification_report_correction_report FOREIGN KEY (report_id)
        REFERENCES visitor_verification_report (id) ON DELETE CASCADE,
    CONSTRAINT fk_visitor_verification_report_correction_requester FOREIGN KEY (requester_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_visitor_verification_report_correction_reviewer FOREIGN KEY (reviewer_admin_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_visitor_verification_report_correction_type CHECK (
        report_type IN (
            'PLACE_INFORMATION', 'OPERATING_HOURS', 'LOCATION', 'CLOSED_PLACE',
            'WAIT_TIME', 'LANGUAGE_SUPPORT', 'COUPON_USAGE', 'CROWD_LEVEL', 'OTHER'
        )
    ),
    CONSTRAINT ck_visitor_verification_report_correction_status CHECK (
        status IN ('SUBMITTED', 'ACCEPTED', 'REJECTED')
    ),
    CONSTRAINT ck_visitor_verification_report_correction_description CHECK (
        length(trim(description)) > 0
    ),
    CONSTRAINT ck_visitor_verification_report_correction_wait_time CHECK (
        wait_time_minutes IS NULL OR wait_time_minutes BETWEEN 0 AND 1440
    ),
    CONSTRAINT ck_visitor_verification_report_correction_language CHECK (
        language_code IS NULL OR language_code ~ '^[a-z]{2,3}(-[A-Z]{2})?$'
    ),
    CONSTRAINT ck_visitor_verification_report_correction_coupon CHECK (
        coupon_usage_status IS NULL OR coupon_usage_status IN ('AVAILABLE', 'UNAVAILABLE', 'UNKNOWN')
    ),
    CONSTRAINT ck_visitor_verification_report_correction_crowd CHECK (
        crowd_level IS NULL OR crowd_level IN ('LOW', 'MODERATE', 'HIGH', 'FULL')
    ),
    CONSTRAINT ck_visitor_verification_report_correction_structured_value CHECK (
        (report_type = 'WAIT_TIME'
            AND wait_time_minutes IS NOT NULL
            AND language_code IS NULL AND coupon_usage_status IS NULL AND crowd_level IS NULL)
        OR (report_type = 'LANGUAGE_SUPPORT'
            AND wait_time_minutes IS NULL
            AND language_code IS NOT NULL AND coupon_usage_status IS NULL AND crowd_level IS NULL)
        OR (report_type = 'COUPON_USAGE'
            AND wait_time_minutes IS NULL
            AND language_code IS NULL AND coupon_usage_status IS NOT NULL AND crowd_level IS NULL)
        OR (report_type = 'CROWD_LEVEL'
            AND wait_time_minutes IS NULL
            AND language_code IS NULL AND coupon_usage_status IS NULL AND crowd_level IS NOT NULL)
        OR (report_type NOT IN ('WAIT_TIME', 'LANGUAGE_SUPPORT', 'COUPON_USAGE', 'CROWD_LEVEL')
            AND wait_time_minutes IS NULL
            AND language_code IS NULL AND coupon_usage_status IS NULL AND crowd_level IS NULL)
    ),
    CONSTRAINT ck_visitor_verification_report_correction_review CHECK (
        (status = 'SUBMITTED' AND reviewer_admin_user_id IS NULL AND reviewed_at IS NULL AND review_note IS NULL)
        OR (status = 'ACCEPTED' AND reviewer_admin_user_id IS NOT NULL AND reviewed_at IS NOT NULL)
        OR (status = 'REJECTED' AND reviewer_admin_user_id IS NOT NULL
            AND reviewed_at IS NOT NULL AND review_note IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_visitor_verification_report_correction_active
    ON visitor_verification_report_correction (report_id)
    WHERE status = 'SUBMITTED';

CREATE INDEX idx_visitor_verification_report_correction_status_created
    ON visitor_verification_report_correction (status, created_at DESC, id DESC);

CREATE INDEX idx_visitor_verification_report_correction_requester_created
    ON visitor_verification_report_correction (requester_user_id, created_at DESC, id DESC);
