CREATE TABLE place_operating_notice (
    place_operating_notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_place_id BIGINT NOT NULL,
    notice_type VARCHAR(30) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    message VARCHAR(500) NOT NULL,
    starts_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    expired_at TIMESTAMP(6),
    canceled_at TIMESTAMP(6),
    cancel_reason VARCHAR(500),
    created_by_user_id BIGINT NOT NULL,
    updated_by_user_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_place_operating_notice_place FOREIGN KEY (map_place_id)
        REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT ck_place_operating_notice_type CHECK (notice_type IN (
        'TEMPORARY_CLOSURE',
        'HOURS_CHANGE',
        'CROWDING',
        'REOPENING',
        'GENERAL'
    )),
    CONSTRAINT ck_place_operating_notice_severity CHECK (severity IN (
        'INFO',
        'WARNING',
        'CRITICAL'
    )),
    CONSTRAINT ck_place_operating_notice_status CHECK (status IN (
        'SCHEDULED',
        'ACTIVE',
        'EXPIRED',
        'CANCELED'
    )),
    CONSTRAINT ck_place_operating_notice_message CHECK (length(trim(message)) > 0),
    CONSTRAINT ck_place_operating_notice_period CHECK (starts_at < expires_at),
    CONSTRAINT ck_place_operating_notice_lifecycle CHECK (
        (
            status IN ('SCHEDULED', 'ACTIVE')
            AND expired_at IS NULL
            AND canceled_at IS NULL
            AND cancel_reason IS NULL
        )
        OR (
            status = 'EXPIRED'
            AND expired_at IS NOT NULL
            AND canceled_at IS NULL
            AND cancel_reason IS NULL
        )
        OR (
            status = 'CANCELED'
            AND expired_at IS NULL
            AND canceled_at IS NOT NULL
            AND cancel_reason IS NOT NULL
        )
    )
);

CREATE UNIQUE INDEX uq_place_operating_notice_active_type
    ON place_operating_notice (map_place_id, notice_type)
    WHERE status IN ('SCHEDULED', 'ACTIVE');

CREATE INDEX idx_place_operating_notice_place_status_period
    ON place_operating_notice (map_place_id, status, starts_at ASC, expires_at ASC);

CREATE INDEX idx_place_operating_notice_expiration
    ON place_operating_notice (status, expires_at ASC, place_operating_notice_id ASC)
    WHERE status IN ('SCHEDULED', 'ACTIVE');

CREATE INDEX idx_place_operating_notice_creator_created
    ON place_operating_notice (created_by_user_id, created_at DESC);
