CREATE TABLE scout_field_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scout_user_id BIGINT,
    place_id BIGINT NOT NULL,
    report_type VARCHAR(30) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    evidence_url VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    reviewer_admin_user_id BIGINT,
    review_note VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    reviewed_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_scout_field_report_scout FOREIGN KEY (scout_user_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_scout_field_report_place FOREIGN KEY (place_id)
        REFERENCES map_place (map_place_id) ON DELETE RESTRICT,
    CONSTRAINT fk_scout_field_report_reviewer FOREIGN KEY (reviewer_admin_user_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_scout_field_report_type CHECK (
        report_type IN (
            'PLACE_INFORMATION', 'OPERATING_HOURS', 'LOCATION', 'CLOSED_PLACE',
            'WAIT_TIME', 'CROWD_LEVEL', 'SAFETY', 'OTHER'
        )
    ),
    CONSTRAINT ck_scout_field_report_status CHECK (
        status IN ('SUBMITTED', 'ACCEPTED', 'REJECTED')
    ),
    CONSTRAINT ck_scout_field_report_description CHECK (
        length(trim(description)) > 0
    ),
    CONSTRAINT ck_scout_field_report_review CHECK (
        (status = 'SUBMITTED' AND reviewer_admin_user_id IS NULL AND reviewed_at IS NULL AND review_note IS NULL)
        OR (status = 'ACCEPTED' AND reviewed_at IS NOT NULL)
        OR (status = 'REJECTED' AND reviewed_at IS NOT NULL AND review_note IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_scout_field_report_active
    ON scout_field_report (scout_user_id, place_id, report_type)
    WHERE status = 'SUBMITTED';

CREATE INDEX idx_scout_field_report_scout_created
    ON scout_field_report (scout_user_id, created_at DESC, id DESC);

CREATE INDEX idx_scout_field_report_status_created
    ON scout_field_report (status, created_at DESC, id DESC);

CREATE INDEX idx_scout_field_report_place_created
    ON scout_field_report (place_id, created_at DESC, id DESC);
