CREATE TABLE place_information_reverification_request (
    place_information_reverification_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_place_id BIGINT NOT NULL,
    place_information_evidence_id BIGINT,
    merchant_owner_user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    requested_by_admin_user_id BIGINT NOT NULL,
    requested_at TIMESTAMP(6) NOT NULL,
    due_at TIMESTAMP(6) NOT NULL,
    last_reminded_at TIMESTAMP(6),
    reminder_count INTEGER NOT NULL DEFAULT 0,
    responded_at TIMESTAMP(6),
    response_note VARCHAR(1000),
    completed_at TIMESTAMP(6),
    canceled_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_place_information_reverification_place FOREIGN KEY (map_place_id)
        REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT fk_place_information_reverification_evidence FOREIGN KEY (place_information_evidence_id)
        REFERENCES place_information_evidence (place_information_evidence_id) ON DELETE SET NULL,
    CONSTRAINT ck_place_information_reverification_status CHECK (status IN (
        'REQUESTED', 'RESPONDED', 'COMPLETED', 'CANCELED', 'EXPIRED'
    )),
    CONSTRAINT ck_place_information_reverification_reason CHECK (length(trim(reason)) > 0),
    CONSTRAINT ck_place_information_reverification_due CHECK (due_at > requested_at),
    CONSTRAINT ck_place_information_reverification_reminder CHECK (
        reminder_count >= 0
        AND ((reminder_count = 0 AND last_reminded_at IS NULL)
            OR (reminder_count > 0 AND last_reminded_at IS NOT NULL))
    ),
    CONSTRAINT ck_place_information_reverification_response CHECK (
        (status = 'REQUESTED' AND responded_at IS NULL AND response_note IS NULL)
        OR (status IN ('RESPONDED', 'COMPLETED') AND responded_at IS NOT NULL
            AND response_note IS NOT NULL AND place_information_evidence_id IS NOT NULL)
        OR status IN ('CANCELED', 'EXPIRED')
    ),
    CONSTRAINT ck_place_information_reverification_terminal CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL AND canceled_at IS NULL)
        OR (status = 'CANCELED' AND canceled_at IS NOT NULL AND completed_at IS NULL)
        OR (status NOT IN ('COMPLETED', 'CANCELED') AND completed_at IS NULL AND canceled_at IS NULL)
    )
);

CREATE UNIQUE INDEX uq_place_information_reverification_active
    ON place_information_reverification_request (map_place_id)
    WHERE status IN ('REQUESTED', 'RESPONDED');

CREATE INDEX idx_place_information_reverification_owner_status
    ON place_information_reverification_request (
        merchant_owner_user_id, status, requested_at DESC, place_information_reverification_request_id DESC
    );

CREATE INDEX idx_place_information_reverification_due
    ON place_information_reverification_request (status, due_at, place_information_reverification_request_id)
    WHERE status = 'REQUESTED';
