CREATE TABLE place_duplicate_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    left_place_id BIGINT NOT NULL,
    right_place_id BIGINT NOT NULL,
    match_reason VARCHAR(30) NOT NULL,
    confidence_score NUMERIC(5, 4) NOT NULL,
    distance_meters INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by_admin_user_id BIGINT,
    review_note VARCHAR(500),
    merge_history_id BIGINT,
    detected_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_place_duplicate_candidate_pair UNIQUE (left_place_id, right_place_id),
    CONSTRAINT fk_place_duplicate_candidate_reviewer FOREIGN KEY (reviewed_by_admin_user_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_place_duplicate_candidate_merge_history FOREIGN KEY (merge_history_id)
        REFERENCES admin_place_merge_history (id) ON DELETE RESTRICT,
    CONSTRAINT ck_place_duplicate_candidate_pair CHECK (left_place_id < right_place_id),
    CONSTRAINT ck_place_duplicate_candidate_match_reason CHECK (match_reason IN (
        'KAKAO_PLACE_ID', 'NAME_ADDRESS_COORDINATE', 'MANUAL_REPORT'
    )),
    CONSTRAINT ck_place_duplicate_candidate_confidence CHECK (
        confidence_score >= 0 AND confidence_score <= 1
    ),
    CONSTRAINT ck_place_duplicate_candidate_distance CHECK (
        distance_meters IS NULL OR distance_meters >= 0
    ),
    CONSTRAINT ck_place_duplicate_candidate_status CHECK (status IN (
        'PENDING', 'CONFIRMED', 'REJECTED', 'MERGED'
    )),
    CONSTRAINT ck_place_duplicate_candidate_review CHECK (
        (status = 'PENDING'
            AND reviewed_by_admin_user_id IS NULL AND review_note IS NULL AND reviewed_at IS NULL)
        OR (status IN ('CONFIRMED', 'REJECTED', 'MERGED')
            AND review_note IS NOT NULL AND length(trim(review_note)) > 0 AND reviewed_at IS NOT NULL)
    ),
    CONSTRAINT ck_place_duplicate_candidate_merge CHECK (
        (status = 'MERGED' AND merge_history_id IS NOT NULL)
        OR (status <> 'MERGED' AND merge_history_id IS NULL)
    ),
    CONSTRAINT ck_place_duplicate_candidate_updated CHECK (updated_at >= detected_at)
);

CREATE INDEX idx_place_duplicate_candidate_status_detected
    ON place_duplicate_candidate (status, detected_at DESC, id DESC);

CREATE INDEX idx_place_duplicate_candidate_left
    ON place_duplicate_candidate (left_place_id, status);

CREATE INDEX idx_place_duplicate_candidate_right
    ON place_duplicate_candidate (right_place_id, status);
