CREATE TABLE verified_boost_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_owner_user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    price_amount BIGINT NOT NULL,
    duration_days INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_verified_boost_product_merchant_owner
        FOREIGN KEY (merchant_owner_user_id) REFERENCES merchant_owner_profile (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_verified_boost_product_place
        FOREIGN KEY (place_id) REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT ck_verified_boost_product_price CHECK (price_amount > 0),
    CONSTRAINT ck_verified_boost_product_duration CHECK (duration_days BETWEEN 1 AND 365),
    CONSTRAINT ck_verified_boost_product_status CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_verified_boost_product_merchant_created
    ON verified_boost_product (merchant_owner_user_id, created_at DESC, id DESC);

CREATE INDEX idx_verified_boost_product_place_status
    ON verified_boost_product (place_id, status, id DESC);
