CREATE TABLE verified_boost_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    price_amount BIGINT NOT NULL,
    duration_days INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_verified_boost_product_price CHECK (price_amount > 0),
    CONSTRAINT ck_verified_boost_product_duration CHECK (duration_days BETWEEN 1 AND 365),
    CONSTRAINT ck_verified_boost_product_status CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_verified_boost_product_status_created
    ON verified_boost_product (status, created_at DESC, id DESC);

CREATE TABLE merchant_verified_boost_selection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    merchant_owner_user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    selected_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_boost_selection_product FOREIGN KEY (product_id) REFERENCES verified_boost_product (id),
    CONSTRAINT fk_boost_selection_owner FOREIGN KEY (merchant_owner_user_id) REFERENCES merchant_owner_profile (user_id),
    CONSTRAINT fk_boost_selection_place FOREIGN KEY (place_id) REFERENCES map_place (map_place_id),
    CONSTRAINT uq_boost_selection_idempotency UNIQUE (merchant_owner_user_id, place_id, idempotency_key)
);

CREATE INDEX idx_boost_selection_owner_selected
    ON merchant_verified_boost_selection (merchant_owner_user_id, selected_at DESC, id DESC);
