CREATE TABLE verified_boost_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    merchant_owner_user_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    ends_at TIMESTAMP(6) NOT NULL,
    stopped_at TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_boost_execution_selection FOREIGN KEY (selection_id)
        REFERENCES merchant_verified_boost_selection (id),
    CONSTRAINT fk_boost_execution_product FOREIGN KEY (product_id)
        REFERENCES verified_boost_product (id),
    CONSTRAINT fk_boost_execution_owner FOREIGN KEY (merchant_owner_user_id)
        REFERENCES merchant_owner_profile (user_id),
    CONSTRAINT fk_boost_execution_place FOREIGN KEY (place_id)
        REFERENCES map_place (map_place_id),
    CONSTRAINT uq_boost_execution_selection UNIQUE (selection_id),
    CONSTRAINT ck_boost_execution_status CHECK (status IN ('ACTIVE', 'STOPPED')),
    CONSTRAINT ck_boost_execution_period CHECK (ends_at > started_at),
    CONSTRAINT ck_boost_execution_stopped_at CHECK (
        (status = 'ACTIVE' AND stopped_at IS NULL)
        OR (status = 'STOPPED' AND stopped_at IS NOT NULL)
    )
);

CREATE INDEX idx_boost_execution_place_window
    ON verified_boost_execution (place_id, status, started_at, ends_at);

CREATE INDEX idx_boost_execution_owner_started
    ON verified_boost_execution (merchant_owner_user_id, started_at DESC, id DESC);
