CREATE TABLE merchant_brand (
    merchant_brand_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_owner_user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    logo_url VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_merchant_brand_owner
        FOREIGN KEY (merchant_owner_user_id) REFERENCES merchant_owner_profile (user_id) ON DELETE CASCADE,
    CONSTRAINT uq_merchant_brand_owner_name UNIQUE (merchant_owner_user_id, name),
    CONSTRAINT uq_merchant_brand_id_owner UNIQUE (merchant_brand_id, merchant_owner_user_id)
);

CREATE INDEX idx_merchant_brand_owner_created
    ON merchant_brand (merchant_owner_user_id, created_at DESC, merchant_brand_id DESC);

CREATE TABLE popup_campaign (
    popup_campaign_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_brand_id BIGINT NOT NULL,
    merchant_owner_user_id BIGINT NOT NULL,
    map_place_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    starts_at TIMESTAMP(6) NOT NULL,
    ends_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_popup_campaign_brand_owner
        FOREIGN KEY (merchant_brand_id, merchant_owner_user_id)
        REFERENCES merchant_brand (merchant_brand_id, merchant_owner_user_id) ON DELETE CASCADE,
    CONSTRAINT fk_popup_campaign_owner
        FOREIGN KEY (merchant_owner_user_id) REFERENCES merchant_owner_profile (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_popup_campaign_place
        FOREIGN KEY (map_place_id) REFERENCES map_place (map_place_id) ON DELETE RESTRICT,
    CONSTRAINT ck_popup_campaign_period CHECK (ends_at > starts_at),
    CONSTRAINT ck_popup_campaign_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CLOSED'))
);

CREATE INDEX idx_popup_campaign_owner_created
    ON popup_campaign (merchant_owner_user_id, created_at DESC, popup_campaign_id DESC);

CREATE INDEX idx_popup_campaign_public_period
    ON popup_campaign (status, starts_at, ends_at, popup_campaign_id DESC);

CREATE INDEX idx_popup_campaign_place_public_period
    ON popup_campaign (map_place_id, status, starts_at, ends_at, popup_campaign_id DESC);
