CREATE TABLE payment_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    tourist_user_id BIGINT NOT NULL,
    merchant_owner_user_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_payment_id VARCHAR(150),
    idempotency_key VARCHAR(100) NOT NULL,
    amount_minor BIGINT,
    currency VARCHAR(3),
    status VARCHAR(20) NOT NULL,
    failure_code VARCHAR(50),
    created_at TIMESTAMP(6) NOT NULL,
    paid_at TIMESTAMP(6),
    failed_at TIMESTAMP(6),
    refunded_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_payment_reservation FOREIGN KEY (reservation_id)
        REFERENCES reservation (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_tourist FOREIGN KEY (tourist_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_merchant_owner FOREIGN KEY (merchant_owner_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT uq_payment_tourist_idempotency UNIQUE (tourist_user_id, idempotency_key),
    CONSTRAINT uq_payment_provider_reference UNIQUE (provider, provider_payment_id),
    CONSTRAINT ck_payment_provider CHECK (provider = UPPER(provider) AND LENGTH(TRIM(provider)) > 0),
    CONSTRAINT ck_payment_amount CHECK (amount_minor IS NULL OR amount_minor > 0),
    CONSTRAINT ck_payment_currency CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_status CHECK (status IN ('PROCESSING', 'PAID', 'REFUND_PROCESSING', 'FAILED', 'REFUNDED')),
    CONSTRAINT ck_payment_state CHECK (
        (status = 'PROCESSING' AND provider_payment_id IS NULL AND amount_minor IS NULL
            AND currency IS NULL AND paid_at IS NULL AND failed_at IS NULL AND refunded_at IS NULL)
        OR (status = 'PAID' AND provider_payment_id IS NOT NULL AND amount_minor IS NOT NULL
            AND currency IS NOT NULL AND paid_at IS NOT NULL AND failed_at IS NULL AND refunded_at IS NULL)
        OR (status = 'REFUND_PROCESSING' AND provider_payment_id IS NOT NULL AND amount_minor IS NOT NULL
            AND currency IS NOT NULL AND paid_at IS NOT NULL AND failed_at IS NULL AND refunded_at IS NULL)
        OR (status = 'FAILED' AND provider_payment_id IS NULL AND amount_minor IS NULL
            AND currency IS NULL AND paid_at IS NULL AND failed_at IS NOT NULL AND failure_code IS NOT NULL
            AND refunded_at IS NULL)
        OR (status = 'REFUNDED' AND provider_payment_id IS NOT NULL AND amount_minor IS NOT NULL
            AND currency IS NOT NULL AND paid_at IS NOT NULL AND failed_at IS NULL AND refunded_at IS NOT NULL)
    )
);

CREATE INDEX idx_payment_tourist_created
    ON payment_transaction (tourist_user_id, created_at DESC, id DESC);

CREATE INDEX idx_payment_merchant_created
    ON payment_transaction (merchant_owner_user_id, created_at DESC, id DESC);

CREATE INDEX idx_payment_reservation_status
    ON payment_transaction (reservation_id, status, created_at, id);

CREATE UNIQUE INDEX uq_payment_reservation_active
    ON payment_transaction (reservation_id)
    WHERE status IN ('PROCESSING', 'PAID', 'REFUND_PROCESSING');

CREATE TABLE settlement_ledger_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_transaction_id BIGINT NOT NULL,
    merchant_owner_user_id BIGINT NOT NULL,
    entry_type VARCHAR(20) NOT NULL,
    gross_amount_minor BIGINT NOT NULL,
    fee_amount_minor BIGINT NOT NULL,
    net_amount_minor BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    settled_at TIMESTAMP(6),
    CONSTRAINT fk_settlement_payment FOREIGN KEY (payment_transaction_id)
        REFERENCES payment_transaction (id) ON DELETE RESTRICT,
    CONSTRAINT fk_settlement_merchant_owner FOREIGN KEY (merchant_owner_user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT uq_settlement_payment_type UNIQUE (payment_transaction_id, entry_type),
    CONSTRAINT ck_settlement_entry_type CHECK (entry_type IN ('PAYMENT', 'REFUND')),
    CONSTRAINT ck_settlement_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_settlement_status CHECK (status IN ('PENDING', 'SETTLED', 'REVERSED')),
    CONSTRAINT ck_settlement_amounts CHECK (
        (entry_type = 'PAYMENT' AND gross_amount_minor > 0 AND fee_amount_minor >= 0
            AND net_amount_minor = gross_amount_minor - fee_amount_minor)
        OR (entry_type = 'REFUND' AND gross_amount_minor < 0 AND fee_amount_minor <= 0
            AND net_amount_minor = gross_amount_minor - fee_amount_minor)
    ),
    CONSTRAINT ck_settlement_state CHECK (
        (status = 'PENDING' AND settled_at IS NULL)
        OR (status = 'SETTLED' AND settled_at IS NOT NULL)
        OR (status = 'REVERSED' AND settled_at IS NULL)
    )
);

CREATE INDEX idx_settlement_merchant_created
    ON settlement_ledger_entry (merchant_owner_user_id, created_at DESC, id DESC);
