ALTER TABLE users
    ADD COLUMN IF NOT EXISTS ban_type VARCHAR(20);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS ban_expires_at TIMESTAMP(6);

UPDATE users
SET ban_type = 'PERMANENT'
WHERE banned = TRUE
  AND ban_type IS NULL;

CREATE TABLE IF NOT EXISTS user_sanction_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id BIGINT NOT NULL,
    target_username VARCHAR(50),
    ban_type VARCHAR(20),
    action VARCHAR(20) NOT NULL,
    reason VARCHAR(255),
    started_at TIMESTAMP(6),
    ended_at TIMESTAMP(6),
    admin_user_id BIGINT,
    admin_username VARCHAR(50),
    processed_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_sanction_history_target_processed
    ON user_sanction_history (target_user_id, processed_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_sanction_history_type_action
    ON user_sanction_history (ban_type, action);
