CREATE TABLE merchant_place_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    invited_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_merchant_place_member_place
        FOREIGN KEY (place_id) REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT fk_merchant_place_member_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_merchant_place_member_inviter
        FOREIGN KEY (invited_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT uq_merchant_place_member_place_user UNIQUE (place_id, user_id),
    CONSTRAINT ck_merchant_place_member_role CHECK (role IN ('OWNER', 'MANAGER', 'STAFF')),
    CONSTRAINT ck_merchant_place_member_status CHECK (status IN ('ACTIVE', 'REVOKED'))
);

CREATE INDEX idx_merchant_place_member_user_status
    ON merchant_place_member (user_id, status);

CREATE TABLE merchant_place_invitation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    invitee_user_id BIGINT NOT NULL,
    invited_by BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    responded_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_merchant_place_invitation_place
        FOREIGN KEY (place_id) REFERENCES map_place (map_place_id) ON DELETE CASCADE,
    CONSTRAINT fk_merchant_place_invitation_invitee
        FOREIGN KEY (invitee_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_merchant_place_invitation_inviter
        FOREIGN KEY (invited_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_merchant_place_invitation_role CHECK (role IN ('MANAGER', 'STAFF')),
    CONSTRAINT ck_merchant_place_invitation_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED'))
);

CREATE UNIQUE INDEX uq_merchant_place_invitation_pending
    ON merchant_place_invitation (place_id, invitee_user_id)
    WHERE status = 'PENDING';

CREATE INDEX idx_merchant_place_invitation_invitee_status
    ON merchant_place_invitation (invitee_user_id, status, created_at DESC);
