CREATE TABLE place_conversion_event (
    place_conversion_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    map_place_id BIGINT NOT NULL,
    conversion_type VARCHAR(20) NOT NULL,
    source_id BIGINT NOT NULL,
    deduplication_key VARCHAR(200) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_place_conversion_event_user CHECK (user_id > 0),
    CONSTRAINT ck_place_conversion_event_place CHECK (map_place_id > 0),
    CONSTRAINT ck_place_conversion_event_source CHECK (source_id > 0),
    CONSTRAINT ck_place_conversion_event_type CHECK (
        conversion_type IN ('RESERVATION', 'BENEFIT')
    ),
    CONSTRAINT uq_place_conversion_event_source UNIQUE (conversion_type, source_id),
    CONSTRAINT uq_place_conversion_event_deduplication_key UNIQUE (deduplication_key)
);

CREATE INDEX idx_place_conversion_event_place_occurred
    ON place_conversion_event (map_place_id, occurred_at DESC, place_conversion_event_id DESC);

CREATE INDEX idx_place_conversion_event_user_occurred
    ON place_conversion_event (user_id, occurred_at DESC, place_conversion_event_id DESC);
