CREATE TABLE admin_role_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL,
    role VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    assigned_by_user_id BIGINT,
    assigned_at TIMESTAMP(6) NOT NULL,
    revoked_at TIMESTAMP(6),
    CONSTRAINT fk_admin_role_assignment_user
        FOREIGN KEY (admin_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_role_assignment_assigner
        FOREIGN KEY (assigned_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_admin_role_assignment_user
        CHECK (admin_user_id > 0),
    CONSTRAINT ck_admin_role_assignment_role
        CHECK (role IN (
            'SUPER_ADMIN',
            'CONTENT_MODERATOR',
            'MERCHANT_OPERATOR',
            'SUPPORT_OPERATOR',
            'ANALYST'
        )),
    CONSTRAINT ck_admin_role_assignment_status
        CHECK (status IN ('ACTIVE', 'REVOKED')),
    CONSTRAINT ck_admin_role_assignment_period
        CHECK (
            (status = 'ACTIVE' AND revoked_at IS NULL)
            OR (status = 'REVOKED' AND revoked_at IS NOT NULL AND revoked_at >= assigned_at)
        )
);

CREATE UNIQUE INDEX uq_admin_role_assignment_active
    ON admin_role_assignment (admin_user_id, role)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_admin_role_assignment_user_status
    ON admin_role_assignment (admin_user_id, status, assigned_at DESC);

INSERT INTO admin_role_assignment (
    admin_user_id, role, status, assigned_by_user_id, assigned_at, revoked_at
)
SELECT u.id, 'SUPER_ADMIN', 'ACTIVE', NULL, COALESCE(u.created_at, CURRENT_TIMESTAMP), NULL
FROM users u
WHERE u.role = 'ADMIN'
  AND NOT EXISTS (
      SELECT 1
      FROM admin_role_assignment existing
      WHERE existing.admin_user_id = u.id
        AND existing.role = 'SUPER_ADMIN'
        AND existing.status = 'ACTIVE'
  );
