CREATE TABLE map_link_conversion_event (
    map_link_conversion_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    map_place_id BIGINT NOT NULL,
    link_type VARCHAR(30) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    deduplication_key VARCHAR(200) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_map_link_conversion_user CHECK (user_id > 0),
    CONSTRAINT ck_map_link_conversion_place CHECK (map_place_id > 0),
    CONSTRAINT ck_map_link_conversion_type CHECK (link_type IN ('DIRECTIONS', 'EXTERNAL_MAP')),
    CONSTRAINT ck_map_link_conversion_provider CHECK (length(trim(provider)) > 0),
    CONSTRAINT uq_map_link_conversion_deduplication UNIQUE (deduplication_key)
);

CREATE INDEX idx_map_link_conversion_place_occurred
    ON map_link_conversion_event (map_place_id, occurred_at DESC, map_link_conversion_event_id DESC);

CREATE INDEX idx_map_link_conversion_user_occurred
    ON map_link_conversion_event (user_id, occurred_at DESC, map_link_conversion_event_id DESC);
