CREATE TABLE data_quality_issue (
    data_quality_issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(40) NOT NULL,
    entity_id BIGINT NOT NULL,
    rule_code VARCHAR(80) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    details VARCHAR(500),
    detected_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP(6),
    CONSTRAINT ck_data_quality_entity CHECK (entity_id > 0),
    CONSTRAINT ck_data_quality_severity CHECK (severity IN ('INFO', 'WARNING', 'ERROR')),
    CONSTRAINT ck_data_quality_status CHECK (status IN ('OPEN', 'RESOLVED', 'IGNORED')),
    CONSTRAINT uq_data_quality_rule_entity UNIQUE (entity_type, entity_id, rule_code, status)
);

CREATE INDEX idx_data_quality_issue_status_detected
    ON data_quality_issue (status, detected_at DESC, data_quality_issue_id DESC);
