CREATE TABLE place_registration_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    place_name VARCHAR(100) NOT NULL,
    category VARCHAR(30) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    road_address VARCHAR(255) NOT NULL,
    jibun_address VARCHAR(255) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    business_registration_file_id VARCHAR(100),
    identity_document_file_id VARCHAR(100),
    representative_image_file_ids VARCHAR(2000),
    review_reason VARCHAR(500),
    reviewer_user_id BIGINT,
    registered_place_id BIGINT UNIQUE,
    submitted_at TIMESTAMP(6),
    reviewed_at TIMESTAMP(6),
    registered_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_place_registration_applicant FOREIGN KEY (applicant_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_place_registration_place FOREIGN KEY (registered_place_id) REFERENCES map_place (map_place_id) ON DELETE SET NULL,
    CONSTRAINT ck_place_registration_status CHECK (status IN ('DRAFT','PENDING','APPROVED','REJECTED','REGISTERED','CANCELED')),
    CONSTRAINT ck_place_registration_category CHECK (category IN ('MUSIC','RESTAURANT','POP_UP','FASHION','BEAUTY','EXHIBITION','CAFE'))
);

CREATE INDEX idx_place_registration_applicant ON place_registration_application (applicant_user_id, updated_at DESC, id DESC);
CREATE INDEX idx_place_registration_status ON place_registration_application (status, updated_at DESC, id DESC);
